apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: app 
  janus-idp.io/tekton: app
  backstage.io/kubernetes-id: app
  backstage.io/kubernetes-namespace: namespace1 
  app.kubernetes.io/part-of: app
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  