apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: app-gitops
  description: This is GitOps manifest for app   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: app
    janus-idp.io/tekton: app 
    backstage.io/kubernetes-id: app 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:app
