apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: app
  janus-idp.io/tekton: app
  backstage.io/kubernetes-id: app
  backstage.io/kubernetes-namespace: namespace1 
  app.kubernetes.io/part-of: app
resources: 
- deployment.yaml
- route.yaml
- service.yaml
